// <auto-generated />
using System;
using Istrate_Alexandra_Proiect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Istrate_Alexandra_Proiect.Migrations
{
    [DbContext(typeof(Istrate_Alexandra_ProiectContext))]
    [Migration("20220108004145_Angajat")]
    partial class Angajat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Istrate_Alexandra_Proiect.Models.Angajat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumePrenumeAngajat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Angajat");
                });

            modelBuilder.Entity("Istrate_Alexandra_Proiect.Models.Apartament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AngajatID")
                        .HasColumnType("int");

                    b.Property<int>("ApId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPublicare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.HasIndex("AngajatID");

                    b.ToTable("Apartament");
                });

            modelBuilder.Entity("Istrate_Alexandra_Proiect.Models.Apartament", b =>
                {
                    b.HasOne("Istrate_Alexandra_Proiect.Models.Angajat", "Angajat")
                        .WithMany("Apartamente")
                        .HasForeignKey("AngajatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Angajat");
                });

            modelBuilder.Entity("Istrate_Alexandra_Proiect.Models.Angajat", b =>
                {
                    b.Navigation("Apartamente");
                });
#pragma warning restore 612, 618
        }
    }
}
